CREATE TABLE post (
	id VARCHAR(36) PRIMARY KEY,
	created_by VARCHAR(100) NOT NULL,
	user_avatar VARCHAR(255) NOT NULL, 
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
	pet_name VARCHAR(100) NOT NULL,
	location VARCHAR(100) NOT NULL,
	photos MEDIUMBLOB NOT NULL,
	description TEXT,
	interactions_count INT DEFAULT 0,
	solved BOOLEAN DEFAULT FALSE
)